  # 核心任务
- name: Kafka
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'kafka_version_selection'
      prompt: "\nPlease choose the number for Kafka version [ 1/../15] \n\n
      1: kafka 3.0.0\n
      2: Kafka 2.8.0\n
      3: Kafka 2.7.1\n
      4: Kafka 2.7.0\n
      5: Kafka 2.6.2\n
      6: Kafka 2.6.1\n
      7: Kafka 2.6.0\n
      8: Kafka 2.5.1\n
      9: Kafka 2.4.1\n
      10: Kafka 2.3.1\n
      11: Kafka 2.2.2\n
      12: Kafka 2.2.1\n
      13: Kafka 1.1.1\n
      14: Kafka 1.1.0\n
      15: Kafka 0.10.2\n"
      private: no
      default: 1
  
  vars:
    kafka_select:
      '1': '3.0.0'
      '2': '2.8.0'
      '3': '2.7.1'
      '4': '2.7.0'
      '5': '2.6.2'
      '6': '2.6.1'
      '7': '2.6.0'
      '8': '2.5.1'
      '9': '2.4.1'
      '10': '2.3.1'
      '11': '2.2.2'
      '12': '2.2.1'
      '13': '1.1.1'
      '14': '1.1.0'
      '15': '0.10.2'

    kafka_version: "{{kafka_select[kafka_version_selection]}}" 

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud"} 
    - { role: role_jdk, tags: "role_jdk"} 
    - { role: role_docker, tags: "role_docker"} 
    - { role: role_kafka, tags: "role_kafka"}
    - { role: role_init, tags: "role_init"}
    - { role: role_preend, tags: "role_preend"}
    - { role: role_end, tags: "role_end" }
